from manim import *

class Area_Vector(ThreeDScene):
    def construct(self):
        self.set_camera_orientation(phi=75*DEGREES, theta=-45*DEGREES)

        space = Square(6, fill_color=BLUE_D, fill_opacity=0.5, stroke_color=WHITE, stroke_width=1)
        vector = Arrow3D(start=space.get_center(), end=(0, 0, 1), color=YELLOW_E)
        vector.set_opacity(1)
        A = Text('A', color=PURE_RED).shift(LEFT*1, DOWN*0.25)
        n = Text('n', color=YELLOW_E,)
        hat = Text('^', color=YELLOW_E)
        n_hat = VGroup(n, hat)
        n_hat.arrange(UP, buff=-0.00000025)
        n_hat.shift(UP*1.5)
        self.add_fixed_in_frame_mobjects(A, n_hat)
        green_A = Text('A', color=PURE_GREEN)
        A_hat_bottom = Line(color=PURE_GREEN, start=(0, 0, 0), end=(0.3, 0, 0))
        A_hat_top = Line(color=PURE_GREEN, start=(0.3, 0, 0), end=(0.2, 0.1, 0.2))
        A_hat = VGroup(A_hat_bottom, A_hat_top)
        answer = VGroup(green_A, A_hat)
        answer.arrange(UP, buff=-0.00000025)
        answer.shift(UP*1, LEFT*1)
        AVector = Arrow3D(start=space.get_center(), end=(0, 0, 2), color=PURE_GREEN)
        cl1 = Line(start=(0, 0, 2), end=(0, 0, 1.2), color=PURE_RED, path_arc=0.5)
        cl2 = Line(start=(0, 0, 0), end=(0, 0, 0.8), color=PURE_RED, path_arc=0.5)
        l1 = Line(start=(0, 0, 1.2), end=(0, 0, 1), color=PURE_RED)
        l2 = Line(start=(0, 0, 0.8), end=(0, 0, 1), color=PURE_RED)
        bracket = VGroup(cl1, l1, l2, cl2).shift(RIGHT*0.1, UP*0.2)
        red_A = Text('A', color=PURE_RED).shift(RIGHT*0.7, UP*1)

        self.play(Write(space), Write(vector), Write(A), Write(n_hat))
        self.wait(1)
        equation = VGroup(A, n_hat)
        equation.arrange(RIGHT, buff=-0.0001)
        equation.shift(UP*1, LEFT*1)
        self.play(n_hat.animate.shift(UP*0.025), A.animate.shift(DOWN*0.025))
        self.wait(1)
        self.play(Transform(equation, answer), Transform(vector, AVector))
        self.wait(1)
        self.play(Write(bracket))
        self.add_fixed_in_frame_mobjects(red_A)
        self.wait(1)
        group = VGroup(space, bracket, vector)
        self.play(group.animate.scale(2), equation.animate.scale(2).shift(LEFT*1), red_A.animate.scale(2).shift(RIGHT*1))
        self.wait(1)
        self.play(group.animate.scale(0.25), equation.animate.scale(0.25).shift(RIGHT*1.5), red_A.animate.scale(0.25).shift(LEFT*1.25))
        self.wait(1)
        self.play(group.animate.scale(2), equation.animate.scale(2).shift(LEFT*0.5), red_A.animate.scale(2).shift(RIGHT*0.5))
        self.wait(1)