from manim import * 
from manim_physics import * 

class Dipole(Scene):
    def construct(self):

        c1 = Charge(1, color = RED)
        c2 = Charge(-1, color = BLUE)
        c2.move_to(2*RIGHT)
        f1 = ElectricField(c1)
        f2 = ElectricField(c2)
        g = NumberPlane()

        self.add(c1, g)
        self.wait(2)
        self.add(f1)
        self.wait(2)
        c1.move_to(2*LEFT)
        f1.move_to(2*LEFT)
        self.add(c2)
        self.wait(2)
        self.add(f2)
        self.wait(2)

        f = ElectricField(c1, c2)

        self.remove(f1, f2)
        self.add(f)
        self.wait(2)

        l1 = Line(start = LEFT * 1 + UP * 0.4, end = RIGHT * 1 + UP * 0.4, color = PINK, path_arc = -0.5).add_tip()
        l2 = Line(start = LEFT * 1 + DOWN * 0.4, end = RIGHT * 1 + DOWN * 0.4, color = PINK, path_arc = 0.5).add_tip()
        l3 = Line(start = LEFT * 1.4 + UP * 0.5, end = RIGHT * 1.4 + UP * 0.5, color = PINK, path_arc = -1.2).add_tip()
        l4 = Line(start = LEFT * 1.4 + DOWN * 0.5, end = RIGHT * 1.4 + DOWN * 0.5, color = PINK, path_arc = 1.2).add_tip()
        l5 = Line(start = LEFT * 1.5 + UP * 1, end = RIGHT * 1.5 + UP * 1, color = PINK, path_arc = -1.4).add_tip()
        l6 = Line(start = LEFT * 1.5 + DOWN * 1, end = RIGHT * 1.5 + DOWN * 1, color = PINK, path_arc = 1.4).add_tip()
        l7 = Line(start = LEFT * 1.6 + UP * 1.5, end = RIGHT * 1.6 + UP * 1.5, color = PINK, path_arc = -1.7).add_tip()
        l8 = Line(start = LEFT * 1.6 + DOWN * 1.5, end = RIGHT * 1.6 + DOWN * 1.5, color = PINK, path_arc = 1.7).add_tip()
        l9 = Line(start = LEFT * 1.7 + UP * 2, end = RIGHT * 1.7 + UP * 2, color = PINK, path_arc = -2).add_tip()
        l10 = Line(start = LEFT * 1.7 + DOWN * 2, end = RIGHT * 1.7 + DOWN * 2, color = PINK, path_arc = 2).add_tip()
        l11 = Line(start = LEFT * 1.8 + UP * 2.5, end = RIGHT * 1.8 + UP * 2.5, color = PINK, path_arc = -2.2).add_tip()
        l12 = Line(start = LEFT * 1.8 + DOWN * 2.5, end = RIGHT * 1.8 + DOWN * 2.5, color = PINK, path_arc = 2.2).add_tip()
        l13 = Line(start = LEFT * 2 + UP * 0.5, end = LEFT * 1.8 + UP * 4, color = PINK, path_arc = -0.3).add_tip()
        l14 = Line(start = LEFT * 2 + DOWN * 0.5, end = LEFT * 1.8 + DOWN * 4, color = PINK, path_arc = 0.3).add_tip()
        l15 = Line(start = RIGHT * 2 + UP * 0.5, end = RIGHT * 1.8 + UP * 4, color = PINK, path_arc = 0.3)
        l16 = Line(start = RIGHT * 2 + DOWN * 0.5, end = RIGHT * 1.8 + DOWN * 4, color = PINK, path_arc = -0.3)
        l17 = Line(start = LEFT * 2.5 + UP * 0.5, end = LEFT * 5.8 + UP * 4, color = PINK, path_arc = -0.3).add_tip()
        l18 = Line(start = LEFT * 2.5 + DOWN * 0.5, end = LEFT * 5.8 + DOWN * 4, color = PINK, path_arc = 0.3).add_tip()
        l19 = Line(start = RIGHT * 2.5 + UP * 0.5, end = RIGHT * 5.8 + UP * 4, color = PINK, path_arc = 0.3)
        l20 = Line(start = RIGHT * 2.5 + DOWN * 0.5, end = RIGHT * 5.8 + DOWN * 4, color = PINK, path_arc = -0.3)
        l21 = Line(start = LEFT * 2.5 + UP * 2, end = LEFT * 2.5 + UP * 4, color = PINK, path_arc = -0.1).add_tip()
        l22 = Line(start = LEFT * 2.5 + DOWN * 2, end = LEFT * 2.5 + DOWN * 4, color = PINK, path_arc = 0.1).add_tip()
        l23 = Line(start = RIGHT * 2.5 + UP * 2, end = RIGHT * 2.5 + UP * 4, color = PINK, path_arc = 0.1)
        l24 = Line(start = RIGHT * 2.5 + DOWN * 2, end = RIGHT * 2.5 + DOWN * 4, color = PINK, path_arc = -0.1)
        l25 = Line(start = LEFT * 2.5 + UP * 1, end = LEFT * 4.7 + UP * 4, color = PINK, path_arc = -0.2).add_tip()
        l26 = Line(start = LEFT * 2.5 + DOWN * 1, end = LEFT * 4.7 + DOWN * 4, color = PINK, path_arc = 0.2).add_tip()
        l27 = Line(start = RIGHT * 2.5 + UP * 1, end = RIGHT * 4.7 + UP * 4, color = PINK, path_arc = 0.2)
        l28 = Line(start = RIGHT * 2.5 + DOWN * 1, end = RIGHT * 4.7 + DOWN * 4, color = PINK, path_arc = -0.2)
        l29 = Line(start = LEFT * 2.5 + UP * 1.5, end = LEFT * 3.5 + UP * 4, color = PINK, path_arc = -0.3).add_tip()
        l30 = Line(start = LEFT * 2.5 + DOWN * 1.5, end = LEFT * 3.5 + DOWN * 4, color = PINK, path_arc = 0.3).add_tip()
        l31 = Line(start = RIGHT * 3.5 + UP * 4, end = RIGHT * 2.5 + UP * 1.5, color = PINK, path_arc = 0.3).add_tip()
        l32 = Line(start = RIGHT * 3.5 + DOWN * 4, end = RIGHT * 2.5 + DOWN * 1.5, color = PINK, path_arc = -0.3).add_tip()
        l33 = Line(start = LEFT * 3 + UP * 0.5, end = LEFT * 7 + UP * 4, color = PINK, path_arc = -0.3).add_tip()
        l34 = Line(start = LEFT * 3 + DOWN * 0.5, end = LEFT * 7 + DOWN * 4, color = PINK, path_arc = 0.3).add_tip()
        l35 = Line(start = RIGHT * 7 + UP * 4, end = RIGHT * 3 + UP * 0.5, color = PINK, path_arc = 0.3).add_tip()
        l36 = Line(start = RIGHT * 7 + DOWN * 4, end = RIGHT * 3 + DOWN * 0.5, color = PINK, path_arc = -0.3).add_tip()
        l37 = Line(start = LEFT * 3.6 + UP * 0.5, end = LEFT * 7 + UP * 3, color = PINK, path_arc = -0.3).add_tip()
        l38 = Line(start = LEFT* 3.6 + DOWN * 0.5, end = LEFT * 7 + DOWN * 3, color = PINK, path_arc = 0.3).add_tip()
        l39 = Line(start = RIGHT * 7 + UP * 3, end = RIGHT * 3.6 + UP * 0.5, color = PINK, path_arc = 0.3).add_tip()
        l40 = Line(start = RIGHT * 7 + DOWN * 3, end = RIGHT * 3.6 + DOWN * 0.5, color = PINK, path_arc = -0.3).add_tip()
        l41 = Line(start = LEFT * 4 + UP * 0.5, end = LEFT * 7 + UP * 1.2, color = PINK, path_arc = -0.2).add_tip()
        l42 = Line(start = LEFT * 4 + DOWN * 0.5, end = LEFT * 7 + DOWN * 1.2, color = PINK, path_arc = 0.2).add_tip()
        l43 = Line(start = RIGHT * 7 + UP * 1.2, end = RIGHT * 4 + UP * 0.5, color = PINK, path_arc = 0.2).add_tip()
        l44 = Line(start = RIGHT * 7 + DOWN * 1.2, end = RIGHT * 4 + DOWN * 0.5, color = PINK, path_arc = -0.2).add_tip()
        l45 = Line(start = LEFT * 3, end = LEFT * 7, color = PINK).add_tip()
        l46 = Line(start = RIGHT * 3, end = RIGHT * 7, color = PINK)
                   
        self.add(l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14, l15, l16, l17, l18, l19, l20, l21, l22, l23, l24, l25, 
                 l26, l27, l28, l29, l30, l31, l32, l33, l34, l35, l36, l37, l38, l39, l40, l41, l42, l43, l44, l45, l46)
        self.remove(f)
        self.wait(2)