from manim import *
from manim_physics import *

class Superposition(Scene): 
    def construct(self):

        c1 = Charge(1)
        c1.shift(LEFT * 3.5)
        f1 = ElectricField(c1)
        f1.shift(LEFT * 3.5)
        g = NumberPlane()
        a1 = Arrow(start = RIGHT * 0.5 + UP * 0.5, end = RIGHT * 0.8 + UP * 0.5)
        a1.shift(LEFT * 3.5)
        a1a = Arrow(start = RIGHT * 0.5 + UP * 0.5, end = RIGHT * 0.5 + UP * 0.85)
        a1a.shift(LEFT * 3.5)
        a2 = Arrow(start = RIGHT * 1 + UP * 1, end = RIGHT * 1.25 + UP * 1)
        a2
        a2a = Arrow(start = RIGHT * 1 + UP * 1, end = RIGHT * 1 + UP * 1.25)
        a2a.shift(LEFT * 3.5)
        a3 = Arrow(start = RIGHT * 1.5 + UP * 1.5, end = RIGHT * 1.7 + UP * 1.5)
        a3
        a3a = Arrow(start = RIGHT * 1.5 + UP * 1.5, end = RIGHT * 1.5 + UP * 1.75)
        a3a.shift(LEFT * 3.5)
        a4 = Arrow(start = RIGHT * 2 + UP * 2, end = RIGHT * 2.2 + UP * 2)
        a4.shift(LEFT * 3.5)
        a4a = Arrow(start = RIGHT * 2 + UP * 2, end = RIGHT * 2 + UP * 2.2)
        a4a.shift(LEFT * 3.5)
        a5 = Arrow(start = RIGHT * 2.5 + UP * 2.5, end = RIGHT * 2.65 + UP * 2.5)
        a5.shift(LEFT * 3.5)
        a5a = Arrow(start = RIGHT * 2.5 + UP * 2.5, end = RIGHT * 2.5 + UP * 2.65)
        a5a.shift(LEFT * 3.5)
        a6 = Arrow(start = RIGHT * 3 + UP * 3, end = RIGHT * 3.15 + UP * 3)
        a6.shift(LEFT * 3.5)
        a6a = Arrow(start = RIGHT * 3 + UP * 3, end = RIGHT * 3 + UP * 3.15)
        a6a.shift(LEFT * 3.5)
        a7 = Arrow(start = RIGHT * 3.5 + UP * 3.5, end = RIGHT * 3.6 + UP * 3.5)
        a7.shift(LEFT * 3.5)
        a7a = Arrow(start = RIGHT * 3.5 + UP * 3.5, end = RIGHT * 3.5 + UP * 3.6)
        a7a.shift(LEFT * 3.5)
        c2 = Charge(1)
        c2.shift(RIGHT * 3.5)
        f2 = ElectricField(c2)
        a8 = Arrow(start = LEFT * 2.5 + UP * 0.49, end = LEFT * 2.2 + UP * 0.49)
        a8a = Arrow(start = LEFT * 2.5 + UP * 0.49, end = LEFT * 2.5 + UP * 0.65)
        a9 = Arrow(start = LEFT * 1.5 + UP * 0.99, end = LEFT * 1.25 + UP * 0.99)
        a9a = Arrow(start = LEFT * 1.5 + UP * 0.99, end = LEFT * 1.5 + UP * 1.15)
        a10 = Arrow(start = LEFT * 0.5 + UP * 1.5, end = LEFT * 0.3 + UP * 1.5)
        a10a = Arrow(start = LEFT * 0.5 + UP * 1.5, end = LEFT * 0.5 + UP * 1.6)
        r1 = Rectangle(height =0.5, width =5, color = BLACK, fill_opacity = 1)
        r1.set_z_index(0)
        r2 = Rectangle(height = 1.6, width = 3.4, color = BLACK, fill_opacity = 1)
        r2.set_z_index(0)
        au1 = Arrow(start = UP * 1, end = UP * 1.5, color = PINK, stroke_width = 6)
        au2 = Arrow(start = UP * 2.5, end = UP * 3, color = PINK, stroke_width = 6)
        au3 = Arrow(start = DOWN * 1, end = DOWN * 1.5, color = PINK, stroke_width = 6)
        au4 = Arrow(start = DOWN * 2.5, end = DOWN * 3, color = PINK, stroke_width = 6)

        self.add(c1, f1, a1, a1a, a2, a2a, a3, a3a, a4, a4a, a5, a5a, a6, a6a, a7, a7a, c2, f2, a8, a8a, a9, a9a, a10, a10a, r1, r2, g, au1, au2, au3, au4)
        self.wait(2)
