from manim import *
from manim_physics import *

class Spring(Scene):
    def construct(self):

        b = Square(side_length = 1, color = GREEN, fill_color=YELLOW, fill_opacity = 1)
        s = SVGMobject("Spring.svg")
        s.scale(1.65).move_to(RIGHT*2.25 + UP*2.15).stretch_to_fit_height(3.5).shift(DOWN*0.05)
        t = Text("m1", color = BLACK)
        t.move_to(b.get_center())
        m = VGroup(b, t)
        m.shift(RIGHT*2)
        r = Rectangle(height = 3, width =6.3, color = WHITE, fill_color = WHITE, fill_opacity = 1)
        r.shift(LEFT*3.625 + DOWN*1.75)
        r2 = Rectangle(height = 3, width = 6.3, color = WHITE, fill_color = WHITE, fill_opacity = 1)
        r2.shift(LEFT*3.625 + UP*1.75)
        c1 = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, -1.1*np.cos(1.15*t)+1.95, 0], t_range=[-2.7, 2.7, 0.01], color=WHITE))
        c1r = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, -1.1*np.cos(1.15*t)+1.95, 0], t_range=[2.7, -2.7, -0.01], color = WHITE))
        c1h = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, -1.1*np.cos(1.15*t)+1.95, 0], t_range=[0, 2.7], color=WHITE))
        c1hr = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, -1.1*np.cos(1.15*t)+1.95, 0], t_range=[2.7, 0, -0.01], color=WHITE))
        c1h2 = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, -1.1*np.cos(1.15*t)+1.95, 0], t_range=[-2.7, 0], color=WHITE))
        c1h2r = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, -1.1*np.cos(1.15*t)+1.95, 0], t_range=[0, -2.7, -0.01], color=WHITE))
        d1 = Dot(point = [-3.5, -1.1*np.cos(1.15*0)+1.95, 0], color = BLACK)
        c2 = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, 1.1*np.cos(1.15*t)-1.55, 0], t_range=[-2.7, 2.7, 0.01], color=WHITE))
        c2r = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, 1.1*np.cos(1.15*t)-1.55, 0], t_range=[2.7, -2.7, -0.01], color = WHITE))
        c2h = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, 1.1*np.cos(1.15*t)-1.55, 0], t_range=[0, 2.7], color=WHITE))
        c2hr = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, 1.1*np.cos(1.15*t)-1.55, 0], t_range=[2.7, 0, -0.01], color=WHITE))
        c2h2 = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, 1.1*np.cos(1.15*t)-1.55, 0], t_range=[-2.7, 0], color=WHITE))
        c2h2r = always_redraw(lambda: ParametricFunction(lambda t: [t-3.5, 1.1*np.cos(1.15*t)-1.55, 0], t_range=[0, -2.7, -0.01], color=WHITE))
        d2 = Dot(point = [-3.5, 1.1*np.cos(1.15*0)-1.55, 0], color = BLACK)
        g1 = Axes(x_range=[-1, 1, 1], y_range = [0, 1, 1], x_length=5.48, y_length=2.2, x_axis_config={"color": PURE_RED, "include_numbers": False, "include_tip": False}, y_axis_config={"color": PURE_RED, "include_numbers": False, "include_tip": False})
        g1.shift(LEFT*3.5 + DOWN*1.55)
        g1y = Text("max KE", color = PURE_RED).scale(0.5).next_to(g1.get_top(), RIGHT*0.3)
        g1x = Text("A", color = PURE_RED).scale(0.5).next_to(g1.get_bottom(), RIGHT*11)
        g1x2 = Text("-A", color = PURE_RED).scale(0.5).next_to(g1.get_bottom(), LEFT*11)
        g1l = Text("Kinetic Energy vs Position", color = PURE_RED).scale(0.6).move_to(LEFT*3.5 + DOWN*3)
        g2 = Axes(x_range=[-1, 1, 1], y_range=[0, 1, 1], x_length=5.48, y_length=2.2, x_axis_config={"color": PURE_BLUE, "include_numbers": False, "include_tip": False}, y_axis_config={"color": PURE_BLUE, "include_numbers": False, "include_tip": False})
        g2.shift(LEFT*3.5 + UP*1.95)
        g2y = Text("max PE", color = PURE_BLUE).scale(0.5).next_to(g2.get_top(), RIGHT*0.3)
        g2x = Text("A", color = PURE_BLUE).scale(0.5).next_to(g2.get_bottom(), RIGHT*11)
        g2x2 = Text("-A", color = PURE_BLUE).scale(0.5).next_to(g2.get_bottom(), LEFT*11)
        g2l = Text("Potential Energy vs Position", color = PURE_BLUE).scale(0.6).move_to(LEFT*3.5 + UP*0.5)
        wr = Rectangle(height = 5, width = 3, color = WHITE, fill_color = WHITE, fill_opacity = 1)
        wr.shift(RIGHT*5)
        c3 = always_redraw(lambda: ParametricFunction(lambda t: [4.25, 2*np.cos(1.15*t), 0], t_range=[-2.7, 2.7, 0.01], color=WHITE))
        c4 = always_redraw(lambda: ParametricFunction(lambda t: [5.75, -2*np.cos(1.15*t), 0], t_range=[-2.7, 2.7, 0.01], color=WHITE))
        l1 = Line(start = RIGHT*4.25 + DOWN*2, end = RIGHT*4.25 + UP*2, color = WHITE)
        l1r = Line(start = RIGHT*4.25 + UP*2, end = RIGHT*4.25 + DOWN*2, color = WHITE)
        l2 = Line(start = RIGHT*5.75 + DOWN*2, end = RIGHT*5.75 + UP*2, color = WHITE)
        l2r = Line(start = RIGHT*5.75 + UP*2, end = RIGHT*5.75 + DOWN*2, color = WHITE)
        d3 = Dot(point = [4.25, 2, 0], color = BLACK)
        d4 = Dot(point = [5.75, -2, 0], color = BLACK)
        KE = Text("KE", color = PURE_RED).scale(0.6).move_to(RIGHT*4.25 + DOWN*2.35)
        PE = Text("PE", color = PURE_BLUE).scale(0.6).move_to(RIGHT*5.75 + DOWN*2.35)
        self.add(s, b, t, r, r2, c1, c2, c1h, c2h, c1r, c2r, c1h2, c2h2, c1hr, c2hr, c1h2r, c2h2r)
        self.add(g1, g2, g1y, g1x, g1x2, g2y, g2x, g2x2, g1l, g2l)
        self.add(wr, c3, c4, l1, l1r, l2, l2r, d3, d4, KE, PE)
        self.add(d1, d2)
        self.wait(2)

        self.play(m.animate.shift(DOWN*2), MoveAlongPath(d1, c1h2r), MoveAlongPath(d2, c2h2r), MoveAlongPath(d3, l1r), MoveAlongPath(d4, l2), s.animate.stretch_to_fit_height(5.5).shift(DOWN*1), run_time = 2)
        self.wait(0.5)
        self.play(m.animate.shift(UP*4), MoveAlongPath(d1, c1), MoveAlongPath(d2, c2), MoveAlongPath(d3, c3), MoveAlongPath(d4, c4), s.animate.stretch_to_fit_height(1.3).shift(UP*2), run_time = 4)
        self.wait(0.25)
        self.play(m.animate.shift(DOWN*2), MoveAlongPath(d1, c1hr), MoveAlongPath(d2, c2hr), MoveAlongPath(d3, l1), MoveAlongPath(d4, l2r), s.animate.stretch_to_fit_height(3.5).shift(DOWN*0.95), run_time = 2)
        self.wait(2)